name: caravanetighmert
favicon: null
layout_spectrum: 0
typography_spectrum: 0.18429
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#44396a'
    - '#e6ad50'
    - '#22c7e6'
    - '#e7283e'
    - '#fffcff'
  brandStrength: 1
  lightness: 0
  saturation: 1
  rhythmicContrast: 0
purpose: []
