name: caravanetighmert
favicon: null
layout_spectrum: 0.919180718017742
typography_spectrum: 0.8070492332335562
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.1363590443506837
  lightness: 0.6583168623037636
  saturation: 0.3656619831454009
  rhythmicContrast: 0.060141524067148566
purpose: []
