name: caravanetighmert
favicon: null
layout_spectrum: 0
typography_spectrum: 0.18429
title: FESTIVAL CARAVANE DE TIGHMERT 2016
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010101'
    - '#a6a29f'
    - '#e5e5e5'
    - '#0f94ad'
    - '#ba05af'
  brandStrength: 0
  lightness: 0
  saturation: 1
  rhythmicContrast: 0
purpose: []
