typography_spectrum: 0.18429
color:
  brandColors:
    - '#160c25'
    - '#cecece'
    - '#645f5b'
    - '#c100ba'
    - '#029999'
  brandStrength: 0
  lightness: 0
  saturation: 1
  rhythmicContrast: 0
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0
analytics:
  google: null
  facebook: null
  twitter: null
author:
  email: caravanetighmert@gmail.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/9ff4dede-6fd6-4ca0-9c8c-7d78d8c8bddc.png
name: caravanetighmert
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: arts vivants 2016
    id: 5bc40e0c-a89f-4c16-aca4-a8f0be2a2a39
    type: content
  - name: arts visuels 2016
    id: c054c91a-0d53-456a-b07a-53ac200277eb
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/84bb184d-043c-4be4-abc1-f84bf9a523e5.png
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: FESTIVAL CARAVANE DE TIGHMERT 2016
purpose: []
